### ISSUE TITLE
Bug: Soil Moisture Title

### ISSUE THREAD

**Issue by jsitters** [quanted/hms_app#12]
https://qedinternal.epa.gov/hms/hydrology/soilmoisture/
Soil Moisture title needs to be two words

Subsurface Flow title needs to be two words
https://qedinternal.epa.gov/hms/hydrology/subsurfaceflow/

Surface Runoff title needs to be two words
https://qedinternal.epa.gov/hms/hydrology/surfacerunoff/

**Comment by deronsmith** [comment]
Resolved issues.
